title: Ross Coulthart # your name (or website title) here
logo: "/images/RC_circle.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have over 18 years’ experience leading modelling and data analysis teams in private sector consultancy. I have worked on a range of projects as part of international multi-disciplinary teams in collaboration with clients and stakeholders. I thrive in an environment that is fast-paced and technically challenging, collaborating to unpick difficult problems and find innovative data-driven solutions.
  <br><br>
  In my current role I apply analytical skills to complex transport problems spanning highways, public transport, active travel and aviation using the latest analytical tools and methods. I have a strong grasp of statistical techniques and a good eye for presenting data in a simple, informative, and visually-engaging way to non-technical audiences.
  <br><br>
  <a href="https://www.linkedin.com/in/ross-coulthart-217471b7">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
